name: "Annotate Semgrep"
description: "GitHub Action for converting Semgrep JSON reports into PR annotations"
author: "Andrei Andreev"
branding:
  icon: "check"
  color: "blue"
inputs:
  json_path:
    description: "Path to the JSON Semgrep report"
    required: true
    default: "results.json"
  output:
    description: "Output file for annotations (use 'stdout' for standard output)"
    required: false
    default: "stdout"
  fail_on:
    description: "Comma-separated list of severity levels that will fail the job (e.g., ERROR,WARNING)"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.json_path }}
    - ${{ inputs.output }}
    - --fail-on=${{ inputs.fail_on }}
